/**
 * Whole words in bopomofo, Wade-Giles, Yale and Gwoyeu Romatzyh, with their
 * tones.
 *
 * Taken from the Mandarin pronunciation blocks of en.wiktionary.org's Chinese
 * entries (CC BY-SA 4.0, retrieved 2026-08-05), one row per page, and committed
 * rather than fetched for the reason [syllabary.ts](syllabary.ts) is: the check
 * runs offline and an edit to a page cannot move the target without a
 * reviewable diff.
 *
 * **It is here because the syllabary cannot see any of this.** That table is
 * 417 rows of toneless spellings, so it says nothing about how a tone is
 * written, where the mark goes, what the neutral tone looks like, what 儿化
 * does to a syllable, or how a word's syllables are joined. Every one of those
 * is a rule this package implements and none of them had an outside check.
 * Four of them turned out to be wrong when this fixture was first run against
 * them — see `docs/romanization/`.
 *
 * A second source rather than more of the first, which is the point: this is a
 * different set of pages, generated by a different piece of software, from
 * Chinese words rather than from a syllable table.
 *
 * Kept as the source writes it. `ʻ` and `ʼ` are the turned comma and the
 * modifier apostrophe, where this package writes an ASCII `'`; the tone digits
 * are raised; proper nouns are capitalised, which this package's writers leave
 * to their callers. The comparison normalises all three.
 */

/**
 * One word, written five ways.
 */
export interface WiktionaryRow {
  /** The page the row came from, in the traditional script it is titled with. */
  readonly hanzi: string;
  /**
   * The source's own pinyin, which is what the other four columns transcribe.
   *
   * A syllable with no tone mark on it is neutral rather than untoned: this
   * source marks every other tone.
   */
  readonly pinyin: string;
  /**
   * The same word with nothing reduced, where the source gives both.
   *
   * Its entries write 太陽 as `tàiyáng → tàiyang`, the second being the form
   * the romanisation columns are written for. The first is where the neutral
   * syllable's original tone comes from, which is the one thing Gwoyeu Romatzyh
   * needs and pinyin never writes: 陽 is still spelled as a second tone in
   * `tay.yang`.
   */
  readonly full?: string;
  readonly zhuyin: string;
  readonly wadeGiles: string;
  readonly yale: string;
  readonly gwoyeu: string;
  /**
   * The cells where the source is wrong, and this package is not.
   *
   * Three of them in 148 rows. They are kept in the table with the source's own
   * text rather than being dropped or corrected, and the test asserts that each
   * one still *fails* to match — so if a page is fixed upstream and the fixture
   * regenerated, the stale exception shows up as a failure rather than as
   * silence.
   *
   * - 事兒 `yale`: the source writes `shìr`, which is pinyin. Yale spells the
   *   empty rhyme as a letter, so 事 shì is `shr̀` and 事兒 is `shr̀r`.
   * - 嗯 `zhuyin`: the source writes ㆭ, U+31AD BOPOMOFO LETTER NGG, which is a
   *   Min Nan letter. The Mandarin syllabic ng is ㄫ, U+312B.
   * - 嗯 `gwoyeu`: the source writes `ng2`, a tone digit rather than a GR
   *   spelling, which is the source declining to invent one. This package
   *   applies the general rules and gets `ngr`; neither is attested.
   */
  readonly except?: readonly ("zhuyin" | "wadeGiles" | "yale" | "gwoyeu")[];
}

/**
 * All 148 rows, in the order they were fetched.
 */
export const WIKTIONARY_WORDS: readonly WiktionaryRow[] = [
  { hanzi: "中國", pinyin: "Zhōngguó", zhuyin: "ㄓㄨㄥ ㄍㄨㄛˊ", wadeGiles: "Chung¹-kuo²", yale: "Jūng-gwó", gwoyeu: "Jonggwo" },
  { hanzi: "北京", pinyin: "Běijīng", zhuyin: "ㄅㄟˇ ㄐㄧㄥ", wadeGiles: "Pei³-ching¹", yale: "Běi-jīng", gwoyeu: "Beeijing" },
  { hanzi: "上海", pinyin: "Shànghǎi", zhuyin: "ㄕㄤˋ ㄏㄞˇ", wadeGiles: "Shang⁴-hai³", yale: "Shàng-hǎi", gwoyeu: "Shanqhae" },
  { hanzi: "臺北", pinyin: "Táiběi", zhuyin: "ㄊㄞˊ ㄅㄟˇ", wadeGiles: "Tʻai²-pei³", yale: "Tái-běi", gwoyeu: "Tairbeei" },
  { hanzi: "香港", pinyin: "Xiānggǎng", zhuyin: "ㄒㄧㄤ ㄍㄤˇ", wadeGiles: "Hsiang¹-kang³", yale: "Syāng-gǎng", gwoyeu: "Shianggaang" },
  { hanzi: "廣東", pinyin: "Guǎngdōng", zhuyin: "ㄍㄨㄤˇ ㄉㄨㄥ", wadeGiles: "Kuang³-tung¹", yale: "Gwǎng-dūng", gwoyeu: "Goangdong" },
  { hanzi: "四川", pinyin: "Sìchuān", zhuyin: "ㄙˋ ㄔㄨㄢ", wadeGiles: "Ssŭ⁴-chʻuan¹", yale: "Sz̀-chwān", gwoyeu: "Syhchuan" },
  { hanzi: "青島", pinyin: "Qīngdǎo", zhuyin: "ㄑㄧㄥ ㄉㄠˇ", wadeGiles: "Chʻing¹-tao³", yale: "Chīng-dǎu", gwoyeu: "Chingdao" },
  { hanzi: "重慶", pinyin: "chóngqìng", zhuyin: "ㄔㄨㄥˊ ㄑㄧㄥˋ", wadeGiles: "chʻung²-chʻing⁴", yale: "chúng-chìng", gwoyeu: "chorngchinq" },
  { hanzi: "天津", pinyin: "Tiānjīn", zhuyin: "ㄊㄧㄢ ㄐㄧㄣ", wadeGiles: "Tʻien¹-chin¹", yale: "Tyān-jīn", gwoyeu: "Tianjin" },
  { hanzi: "西安", pinyin: "Xī'ān", zhuyin: "ㄒㄧ ㄢ", wadeGiles: "Hsi¹-an¹", yale: "Syī-ān", gwoyeu: "Shian" },
  { hanzi: "南京", pinyin: "Nánjīng", zhuyin: "ㄋㄢˊ ㄐㄧㄥ", wadeGiles: "Nan²-ching¹", yale: "Nán-jīng", gwoyeu: "Nanjing" },
  { hanzi: "孔子", pinyin: "Kǒngzǐ", zhuyin: "ㄎㄨㄥˇ ㄗˇ", wadeGiles: "Kʻung³-tzŭ³", yale: "Kǔng-dž", gwoyeu: "Koongtzyy" },
  { hanzi: "東西", pinyin: "dōngxī", zhuyin: "ㄉㄨㄥ ㄒㄧ", wadeGiles: "tung¹-hsi¹", yale: "dūng-syī", gwoyeu: "dongshi" },
  { hanzi: "朋友", pinyin: "péngyou", zhuyin: "ㄆㄥˊ ˙ㄧㄡ", wadeGiles: "pʻêng²-yu⁵", yale: "péng-you", gwoyeu: "perng.iou" },
  { hanzi: "先生", pinyin: "xiānsheng", full: "xiānshēng", zhuyin: "ㄒㄧㄢ ˙ㄕㄥ", wadeGiles: "hsien¹-shêng⁵", yale: "syān-sheng", gwoyeu: "shian.sheng" },
  { hanzi: "學生", pinyin: "xuésheng", full: "xuéshēng", zhuyin: "ㄒㄩㄝˊ ˙ㄕㄥ", wadeGiles: "hsüeh²-shêng⁵", yale: "sywé-sheng", gwoyeu: "shyue.sheng" },
  { hanzi: "什麼", pinyin: "shénme", zhuyin: "ㄕㄣˊ ˙ㄇㄜ", wadeGiles: "shên²-mê⁵", yale: "shén-me", gwoyeu: "shern.me" },
  { hanzi: "我們", pinyin: "wǒmen", zhuyin: "ㄨㄛˇ ˙ㄇㄣ", wadeGiles: "wo³-mên⁵", yale: "wǒ-men", gwoyeu: "woo.men" },
  { hanzi: "桌子", pinyin: "zhuōzi", zhuyin: "ㄓㄨㄛ ˙ㄗ", wadeGiles: "cho¹-tzŭ⁵", yale: "jwō-dz", gwoyeu: "juo.tzy" },
  { hanzi: "喜歡", pinyin: "xǐhuan", zhuyin: "ㄒㄧˇ ˙ㄏㄨㄢ", wadeGiles: "hsi³-huan⁵", yale: "syǐ-hwan", gwoyeu: "shii.huan" },
  { hanzi: "漂亮", pinyin: "piàoliang", zhuyin: "ㄆㄧㄠˋ ˙ㄌㄧㄤ", wadeGiles: "pʻiao⁴-liang⁵", yale: "pyàu-lyang", gwoyeu: "piaw.liang" },
  { hanzi: "謝謝", pinyin: "xièxie", zhuyin: "ㄒㄧㄝˋ ˙ㄒㄧㄝ", wadeGiles: "hsieh⁴-hsieh⁵", yale: "syè-sye", gwoyeu: "shieh.shie" },
  { hanzi: "兒子", pinyin: "érzi", zhuyin: "ㄦˊ ˙ㄗ", wadeGiles: "êrh²-tzŭ⁵", yale: "ér-dz", gwoyeu: "erl.tzy" },
  { hanzi: "女兒", pinyin: "nǚ'ér", zhuyin: "ㄋㄩˇ ㄦˊ", wadeGiles: "nü³-êrh²", yale: "nyǔ-ér", gwoyeu: "neuerl" },
  { hanzi: "豆腐", pinyin: "dòufu", zhuyin: "ㄉㄡˋ ˙ㄈㄨ", wadeGiles: "tou⁴-fu⁵", yale: "dòu-fu", gwoyeu: "dow.fu" },
  { hanzi: "功夫", pinyin: "gōngfu", zhuyin: "ㄍㄨㄥ ˙ㄈㄨ", wadeGiles: "kung¹-fu⁵", yale: "gūng-fu", gwoyeu: "gong.fu" },
  { hanzi: "這兒", pinyin: "zhèr", zhuyin: "ㄓㄜˋㄦ", wadeGiles: "chê⁴-ʼrh", yale: "jèr", gwoyeu: "jehl" },
  { hanzi: "那兒", pinyin: "nàr", zhuyin: "ㄋㄚˋㄦ", wadeGiles: "na⁴-ʼrh", yale: "nàr", gwoyeu: "nall" },
  { hanzi: "哪兒", pinyin: "nǎr", zhuyin: "ㄋㄚˇㄦ", wadeGiles: "na³-ʼrh", yale: "nǎr", gwoyeu: "naal" },
  { hanzi: "玩兒", pinyin: "wánr", zhuyin: "ㄨㄢˊㄦ", wadeGiles: "wan²-ʼrh", yale: "wánr", gwoyeu: "wal" },
  { hanzi: "花兒", pinyin: "huār", zhuyin: "ㄏㄨㄚㄦ", wadeGiles: "hua¹-ʼrh", yale: "hwār", gwoyeu: "hual" },
  { hanzi: "事兒", pinyin: "shìr", zhuyin: "ㄕˋㄦ", wadeGiles: "shih⁴-ʼrh", yale: "shìr", gwoyeu: "shell", except: ["yale"] },
  { hanzi: "小孩兒", pinyin: "xiǎoháir", zhuyin: "ㄒㄧㄠˇ ㄏㄞˊㄦ", wadeGiles: "hsiao³-hai²-ʼrh", yale: "syǎu-háir", gwoyeu: "sheauharl" },
  { hanzi: "知識", pinyin: "zhīshi", zhuyin: "ㄓ ˙ㄕ", wadeGiles: "chih¹-shih⁵", yale: "jr̄-shr", gwoyeu: "jy.shy" },
  { hanzi: "日本", pinyin: "Rìběn", zhuyin: "ㄖˋ ㄅㄣˇ", wadeGiles: "Jih⁴-pên³", yale: "R̀-běn", gwoyeu: "Ryhbeen" },
  { hanzi: "詞典", pinyin: "cídiǎn", zhuyin: "ㄘˊ ㄉㄧㄢˇ", wadeGiles: "tzʻŭ²-tien³", yale: "tsź-dyǎn", gwoyeu: "tsyrdean" },
  { hanzi: "四十", pinyin: "sìshí", zhuyin: "ㄙˋ ㄕˊ", wadeGiles: "ssŭ⁴-shih²", yale: "sz̀-shŕ", gwoyeu: "syhshyr" },
  { hanzi: "學習", pinyin: "xuéxí", zhuyin: "ㄒㄩㄝˊ ㄒㄧˊ", wadeGiles: "hsüeh²-hsi²", yale: "sywé-syí", gwoyeu: "shyueshyi" },
  { hanzi: "決定", pinyin: "juédìng", zhuyin: "ㄐㄩㄝˊ ㄉㄧㄥˋ", wadeGiles: "chüeh²-ting⁴", yale: "jywé-dìng", gwoyeu: "jyuedinq" },
  { hanzi: "軍隊", pinyin: "jūnduì", zhuyin: "ㄐㄩㄣ ㄉㄨㄟˋ", wadeGiles: "chün¹-tui⁴", yale: "jyūn-dwèi", gwoyeu: "jiunduey" },
  { hanzi: "雲南", pinyin: "Yúnnán", zhuyin: "ㄩㄣˊ ㄋㄢˊ", wadeGiles: "Yün²-nan²", yale: "Yún-nán", gwoyeu: "Yunnan" },
  { hanzi: "綠色", pinyin: "lǜsè", zhuyin: "ㄌㄩˋ ㄙㄜˋ", wadeGiles: "lü⁴-sê⁴", yale: "lyù-sè", gwoyeu: "liuhseh" },
  { hanzi: "女人", pinyin: "nǚrén", zhuyin: "ㄋㄩˇ ㄖㄣˊ", wadeGiles: "nü³-jên²", yale: "nyǔ-rén", gwoyeu: "neuren" },
  { hanzi: "六十", pinyin: "liùshí", zhuyin: "ㄌㄧㄡˋ ㄕˊ", wadeGiles: "liu⁴-shih²", yale: "lyòu-shŕ", gwoyeu: "liowshyr" },
  { hanzi: "春天", pinyin: "chūntian", full: "chūntiān", zhuyin: "ㄔㄨㄣ ˙ㄊㄧㄢ", wadeGiles: "chʻun¹-tʻien⁵", yale: "chwūn-tyan", gwoyeu: "chuen.tian" },
  { hanzi: "論文", pinyin: "lùnwén", zhuyin: "ㄌㄨㄣˋ ㄨㄣˊ", wadeGiles: "lun⁴-wên²", yale: "lwùn-wén", gwoyeu: "luennwen" },
  { hanzi: "熊貓", pinyin: "xióngmāo", zhuyin: "ㄒㄩㄥˊ ㄇㄠ", wadeGiles: "hsiung²-mao¹", yale: "syúng-māu", gwoyeu: "shyongmhau" },
  { hanzi: "藝術", pinyin: "yìshu", full: "yìshù", zhuyin: "ㄧˋ ˙ㄕㄨ", wadeGiles: "i⁴-shu⁵", yale: "yì-shu", gwoyeu: "yih.shuh" },
  { hanzi: "王國", pinyin: "wángguó", zhuyin: "ㄨㄤˊ ㄍㄨㄛˊ", wadeGiles: "wang²-kuo²", yale: "wáng-gwó", gwoyeu: "wanggwo" },
  { hanzi: "請問", pinyin: "qǐngwèn", zhuyin: "ㄑㄧㄥˇ ㄨㄣˋ", wadeGiles: "chʻing³-wên⁴", yale: "chǐng-wèn", gwoyeu: "chiingwenn" },
  { hanzi: "洗澡", pinyin: "xǐzǎo", zhuyin: "ㄒㄧˇ ㄗㄠˇ", wadeGiles: "hsi³-tsao³", yale: "syǐ-dzǎu", gwoyeu: "shiitzao" },
  { hanzi: "出去", pinyin: "chūqu", full: "chūqù", zhuyin: "ㄔㄨ ˙ㄑㄩ", wadeGiles: "chʻu¹-chʻü⁵", yale: "chū-chyu", gwoyeu: "chu.chiuh" },
  { hanzi: "太陽", pinyin: "tàiyang", full: "tàiyáng", zhuyin: "ㄊㄞˋ ˙ㄧㄤ", wadeGiles: "tʻai⁴-yang⁵", yale: "tài-yang", gwoyeu: "tay.yang" },
  { hanzi: "天氣", pinyin: "tiānqi", full: "tiānqì", zhuyin: "ㄊㄧㄢ ˙ㄑㄧ", wadeGiles: "tʻien¹-chʻi⁵", yale: "tyān-chi", gwoyeu: "tian.chih" },
  { hanzi: "電話", pinyin: "diànhuà", zhuyin: "ㄉㄧㄢˋ ㄏㄨㄚˋ", wadeGiles: "tien⁴-hua⁴", yale: "dyàn-hwà", gwoyeu: "diannhuah" },
  { hanzi: "咖啡", pinyin: "kāfēi", zhuyin: "ㄎㄚ ㄈㄟ", wadeGiles: "kʻa¹-fei¹", yale: "kā-fēi", gwoyeu: "kafei" },
  { hanzi: "飛機", pinyin: "fēijī", zhuyin: "ㄈㄟ ㄐㄧ", wadeGiles: "fei¹-chi¹", yale: "fēi-jī", gwoyeu: "feiji" },
  { hanzi: "教育", pinyin: "jiàoyu", full: "jiàoyù", zhuyin: "ㄐㄧㄠˋ ˙ㄩ", wadeGiles: "chiao⁴-yü⁵", yale: "jyàu-yu", gwoyeu: "jiaw.yuh" },
  { hanzi: "顏色", pinyin: "yánsè", zhuyin: "ㄧㄢˊ ㄙㄜˋ", wadeGiles: "yen²-sê⁴", yale: "yán-sè", gwoyeu: "yanseh" },
  { hanzi: "昨天", pinyin: "zuótian", full: "zuótiān", zhuyin: "ㄗㄨㄛˊ ˙ㄊㄧㄢ", wadeGiles: "tso²-tʻien⁵", yale: "dzwó-tyan", gwoyeu: "tzwo.tian" },
  { hanzi: "醫院", pinyin: "yīyuàn", zhuyin: "ㄧ ㄩㄢˋ", wadeGiles: "i¹-yüan⁴", yale: "yī-ywàn", gwoyeu: "iyuann" },
  { hanzi: "火車", pinyin: "huǒchē", zhuyin: "ㄏㄨㄛˇ ㄔㄜ", wadeGiles: "huo³-chʻê¹", yale: "hwǒ-chē", gwoyeu: "huooche" },
  { hanzi: "工作", pinyin: "gōngzuò", zhuyin: "ㄍㄨㄥ ㄗㄨㄛˋ", wadeGiles: "kung¹-tso⁴", yale: "gūng-dzwò", gwoyeu: "gongtzuoh" },
  { hanzi: "快樂", pinyin: "kuàile", full: "kuàilè", zhuyin: "ㄎㄨㄞˋ ˙ㄌㄜ", wadeGiles: "kʻuai⁴-lê⁵", yale: "kwài-le", gwoyeu: "kuay.leh" },
  { hanzi: "麻煩", pinyin: "máfan", zhuyin: "ㄇㄚˊ ˙ㄈㄢ", wadeGiles: "ma²-fan⁵", yale: "má-fan", gwoyeu: "ma.fan" },
  { hanzi: "明白", pinyin: "míngbai", zhuyin: "ㄇㄧㄥˊ ˙ㄅㄞ", wadeGiles: "ming²-pai⁵", yale: "míng-bai", gwoyeu: "ming.bai" },
  { hanzi: "外國", pinyin: "wàiguó", zhuyin: "ㄨㄞˋ ㄍㄨㄛˊ", wadeGiles: "wai⁴-kuo²", yale: "wài-gwó", gwoyeu: "waygwo" },
  { hanzi: "社會", pinyin: "shèhuì", zhuyin: "ㄕㄜˋ ㄏㄨㄟˋ", wadeGiles: "shê⁴-hui⁴", yale: "shè-hwèi", gwoyeu: "shehhuey" },
  { hanzi: "問題", pinyin: "wèntí", zhuyin: "ㄨㄣˋ ㄊㄧˊ", wadeGiles: "wên⁴-tʻi²", yale: "wèn-tí", gwoyeu: "wenntyi" },
  { hanzi: "時間", pinyin: "shíjiān", zhuyin: "ㄕˊ ㄐㄧㄢ", wadeGiles: "shih²-chien¹", yale: "shŕ-jyān", gwoyeu: "shyrjian" },
  { hanzi: "現在", pinyin: "xiànzài", zhuyin: "ㄒㄧㄢˋ ㄗㄞˋ", wadeGiles: "hsien⁴-tsai⁴", yale: "syàn-dzài", gwoyeu: "shianntzay" },
  { hanzi: "可以", pinyin: "kěyǐ", zhuyin: "ㄎㄜˇ ㄧˇ", wadeGiles: "kʻo³-i³", yale: "kě-yǐ", gwoyeu: "keeyii" },
  { hanzi: "因為", pinyin: "yīnwei", full: "yīnwèi", zhuyin: "ㄧㄣ ˙ㄨㄟ", wadeGiles: "yin¹-wei⁵", yale: "yīn-wei", gwoyeu: "in.wey" },
  { hanzi: "沒有", pinyin: "méiyou", full: "méiyǒu", zhuyin: "ㄇㄟˊ ˙ㄧㄡ", wadeGiles: "mei²-yu⁵", yale: "méi-you", gwoyeu: "mei.yeou" },
  { hanzi: "知道", pinyin: "zhīdao", full: "zhīdào", zhuyin: "ㄓ ˙ㄉㄠ", wadeGiles: "chih¹-tao⁵", yale: "jr̄-dau", gwoyeu: "jy.daw" },
  { hanzi: "覺得", pinyin: "juéde", zhuyin: "ㄐㄩㄝˊ ˙ㄉㄜ", wadeGiles: "chüeh²-tê⁵", yale: "jywé-de", gwoyeu: "jyue.de" },
  { hanzi: "一會兒", pinyin: "yīhuìr", zhuyin: "ㄧ ㄏㄨㄟˋㄦ", wadeGiles: "i¹-hui⁴-ʼrh", yale: "yī-hwèir", gwoyeu: "ihuell" },
  { hanzi: "味兒", pinyin: "wèir", zhuyin: "ㄨㄟˋㄦ", wadeGiles: "wei⁴-ʼrh", yale: "wèir", gwoyeu: "well" },
  { hanzi: "門兒", pinyin: "ménr", zhuyin: "ㄇㄣˊㄦ", wadeGiles: "mên²-ʼrh", yale: "ménr", gwoyeu: "mel" },
  { hanzi: "鳥兒", pinyin: "niǎor", zhuyin: "ㄋㄧㄠˇㄦ", wadeGiles: "niao³-ʼrh", yale: "nyǎur", gwoyeu: "neaul" },
  { hanzi: "畫兒", pinyin: "huàr", zhuyin: "ㄏㄨㄚˋㄦ", wadeGiles: "hua⁴-ʼrh", yale: "hwàr", gwoyeu: "huall" },
  { hanzi: "老頭兒", pinyin: "lǎotóur", zhuyin: "ㄌㄠˇ ㄊㄡˊㄦ", wadeGiles: "lao³-tʻou²-ʼrh", yale: "lǎu-tóur", gwoyeu: "laotourl" },
  { hanzi: "有點兒", pinyin: "yǒudiǎnr", zhuyin: "ㄧㄡˇ ㄉㄧㄢˇㄦ", wadeGiles: "yu³-tien³-ʼrh", yale: "yǒu-dyǎnr", gwoyeu: "yeoudeal" },
  { hanzi: "好玩兒", pinyin: "hǎowánr", zhuyin: "ㄏㄠˇ ㄨㄢˊㄦ", wadeGiles: "hao³-wan²-ʼrh", yale: "hǎu-wánr", gwoyeu: "haowal" },
  { hanzi: "今兒", pinyin: "jīnr", zhuyin: "ㄐㄧㄣㄦ", wadeGiles: "chin¹-ʼrh", yale: "jīnr", gwoyeu: "jiel" },
  { hanzi: "旅行", pinyin: "lǚxíng", zhuyin: "ㄌㄩˇ ㄒㄧㄥˊ", wadeGiles: "lü³-hsing²", yale: "lyǔ-syíng", gwoyeu: "leushyng" },
  { hanzi: "綠茶", pinyin: "lǜchá", zhuyin: "ㄌㄩˋ ㄔㄚˊ", wadeGiles: "lü⁴-chʻa²", yale: "lyù-chá", gwoyeu: "liuhchar" },
  { hanzi: "決心", pinyin: "juéxīn", zhuyin: "ㄐㄩㄝˊ ㄒㄧㄣ", wadeGiles: "chüeh²-hsin¹", yale: "jywé-syīn", gwoyeu: "jyueshin" },
  { hanzi: "群眾", pinyin: "qúnzhòng", zhuyin: "ㄑㄩㄣˊ ㄓㄨㄥˋ", wadeGiles: "chʻün²-chung⁴", yale: "chyún-jùng", gwoyeu: "chyunjonq" },
  { hanzi: "用功", pinyin: "yònggōng", zhuyin: "ㄩㄥˋ ㄍㄨㄥ", wadeGiles: "yung⁴-kung¹", yale: "yùng-gūng", gwoyeu: "yonqgong" },
  { hanzi: "二十", pinyin: "èrshí", zhuyin: "ㄦˋ ㄕˊ", wadeGiles: "êrh⁴-shih²", yale: "èr-shŕ", gwoyeu: "ellshyr" },
  { hanzi: "而且", pinyin: "érqiě", zhuyin: "ㄦˊ ㄑㄧㄝˇ", wadeGiles: "êrh²-chʻieh³", yale: "ér-chyě", gwoyeu: "erlchiee" },
  { hanzi: "耳朵", pinyin: "ěrduo", zhuyin: "ㄦˇ ˙ㄉㄨㄛ", wadeGiles: "êrh³-to⁵", yale: "ěr-dwo", gwoyeu: "eel.duo" },
  { hanzi: "兒童", pinyin: "értóng", zhuyin: "ㄦˊ ㄊㄨㄥˊ", wadeGiles: "êrh²-tʻung²", yale: "ér-túng", gwoyeu: "erltorng" },
  { hanzi: "白色", pinyin: "báisè", zhuyin: "ㄅㄞˊ ㄙㄜˋ", wadeGiles: "pai²-sê⁴", yale: "bái-sè", gwoyeu: "bairseh" },
  { hanzi: "佛教", pinyin: "Fójiào", zhuyin: "ㄈㄛˊ ㄐㄧㄠˋ", wadeGiles: "Fo²-chiao⁴", yale: "Fwó-jyàu", gwoyeu: "Forjiaw" },
  { hanzi: "波浪", pinyin: "bōlàng", zhuyin: "ㄅㄛ ㄌㄤˋ", wadeGiles: "po¹-lang⁴", yale: "bwō-làng", gwoyeu: "bolanq" },
  { hanzi: "破壞", pinyin: "pòhuài", zhuyin: "ㄆㄛˋ ㄏㄨㄞˋ", wadeGiles: "pʻo⁴-huai⁴", yale: "pwò-hwài", gwoyeu: "pohhuay" },
  { hanzi: "若干", pinyin: "ruògān", zhuyin: "ㄖㄨㄛˋ ㄍㄢ", wadeGiles: "jo⁴-kan¹", yale: "rwò-gān", gwoyeu: "ruohgan" },
  { hanzi: "瑞士", pinyin: "Ruìshi", full: "Ruìshì", zhuyin: "ㄖㄨㄟˋ ˙ㄕ", wadeGiles: "Jui⁴-shih⁵", yale: "Rwèi-shr", gwoyeu: "Ruey.shyh" },
  { hanzi: "雙方", pinyin: "shuāngfāng", zhuyin: "ㄕㄨㄤ ㄈㄤ", wadeGiles: "shuang¹-fang¹", yale: "shwāng-fāng", gwoyeu: "shuangfang" },
  { hanzi: "說話", pinyin: "shuōhuà", zhuyin: "ㄕㄨㄛ ㄏㄨㄚˋ", wadeGiles: "shuo¹-hua⁴", yale: "shwō-hwà", gwoyeu: "shuohuah" },
  { hanzi: "水果", pinyin: "shuǐguǒ", zhuyin: "ㄕㄨㄟˇ ㄍㄨㄛˇ", wadeGiles: "shui³-kuo³", yale: "shwěi-gwǒ", gwoyeu: "shoeiguoo" },
  { hanzi: "睡覺", pinyin: "shuìjiào", zhuyin: "ㄕㄨㄟˋ ㄐㄧㄠˋ", wadeGiles: "shui⁴-chiao⁴", yale: "shwèi-jyàu", gwoyeu: "shueyjiaw" },
  { hanzi: "吹牛", pinyin: "chuīniú", zhuyin: "ㄔㄨㄟ ㄋㄧㄡˊ", wadeGiles: "chʻui¹-niu²", yale: "chwēi-nyóu", gwoyeu: "chueiniou" },
  { hanzi: "純潔", pinyin: "chúnjié", zhuyin: "ㄔㄨㄣˊ ㄐㄧㄝˊ", wadeGiles: "chʻun²-chieh²", yale: "chwún-jyé", gwoyeu: "chwenjye" },
  { hanzi: "尊重", pinyin: "zūnzhòng", zhuyin: "ㄗㄨㄣ ㄓㄨㄥˋ", wadeGiles: "tsun¹-chung⁴", yale: "dzwūn-jùng", gwoyeu: "tzuenjonq" },
  { hanzi: "存在", pinyin: "cúnzài", zhuyin: "ㄘㄨㄣˊ ㄗㄞˋ", wadeGiles: "tsʻun²-tsai⁴", yale: "tswún-dzài", gwoyeu: "tswentzay" },
  { hanzi: "錯誤", pinyin: "cuòwu", full: "cuòwù", zhuyin: "ㄘㄨㄛˋ ˙ㄨ", wadeGiles: "tsʻo⁴-wu⁵", yale: "tswò-wu", gwoyeu: "tsuoh.wuh" },
  { hanzi: "措施", pinyin: "cuòshī", zhuyin: "ㄘㄨㄛˋ ㄕ", wadeGiles: "tsʻo⁴-shih¹", yale: "tswò-shr̄", gwoyeu: "tsuohshy" },
  { hanzi: "女子", pinyin: "nǚzǐ", zhuyin: "ㄋㄩˇ ㄗˇ", wadeGiles: "nü³-tzŭ³", yale: "nyǔ-dž", gwoyeu: "neutzyy" },
  { hanzi: "翁", pinyin: "wēng", zhuyin: "ㄨㄥ", wadeGiles: "wêng¹", yale: "wēng", gwoyeu: "ueng" },
  { hanzi: "嗯", pinyin: "ńg", zhuyin: "ㆭˊ", wadeGiles: "ng²", yale: "ńg", gwoyeu: "ng2", except: ["zhuyin", "gwoyeu"] },
  { hanzi: "恩", pinyin: "ēn", zhuyin: "ㄣ", wadeGiles: "ên¹", yale: "ēn", gwoyeu: "en" },
  { hanzi: "安全", pinyin: "ānquán", zhuyin: "ㄢ ㄑㄩㄢˊ", wadeGiles: "an¹-chʻüan²", yale: "ān-chywán", gwoyeu: "anchyuan" },
  { hanzi: "歐洲", pinyin: "Ōuzhōu", zhuyin: "ㄡ ㄓㄡ", wadeGiles: "Ou¹-chou¹", yale: "Ōu-jōu", gwoyeu: "Oujou" },
  { hanzi: "牛奶", pinyin: "niúnǎi", zhuyin: "ㄋㄧㄡˊ ㄋㄞˇ", wadeGiles: "niu²-nai³", yale: "nyóu-nǎi", gwoyeu: "niounae" },
  { hanzi: "拼音", pinyin: "pīnyīn", zhuyin: "ㄆㄧㄣ ㄧㄣ", wadeGiles: "pʻin¹-yin¹", yale: "pīn-yīn", gwoyeu: "pinin" },
  { hanzi: "西瓜", pinyin: "xīgua", full: "xīguā", zhuyin: "ㄒㄧ ˙ㄍㄨㄚ", wadeGiles: "hsi¹-kua⁵", yale: "syī-gwa", gwoyeu: "shi.gua" },
  { hanzi: "月亮", pinyin: "yuèliang", zhuyin: "ㄩㄝˋ ˙ㄌㄧㄤ", wadeGiles: "yüeh⁴-liang⁵", yale: "ywè-lyang", gwoyeu: "yueh.liang" },
  { hanzi: "永遠", pinyin: "yǒngyuǎn", zhuyin: "ㄩㄥˇ ㄩㄢˇ", wadeGiles: "yung³-yüan³", yale: "yǔng-ywǎn", gwoyeu: "yeongyeuan" },
  { hanzi: "雨傘", pinyin: "yǔsǎn", zhuyin: "ㄩˇ ㄙㄢˇ", wadeGiles: "yü³-san³", yale: "yǔ-sǎn", gwoyeu: "yeusaan" },
  { hanzi: "玉米", pinyin: "yùmi", full: "yùmǐ", zhuyin: "ㄩˋ ˙ㄇㄧ", wadeGiles: "yü⁴-mi⁵", yale: "yù-mi", gwoyeu: "yuh.mii" },
  { hanzi: "運動", pinyin: "yùndong", full: "yùndòng", zhuyin: "ㄩㄣˋ ˙ㄉㄨㄥ", wadeGiles: "yün⁴-tung⁵", yale: "yùn-dung", gwoyeu: "yunn.donq" },
  { hanzi: "遠方", pinyin: "yuǎnfāng", zhuyin: "ㄩㄢˇ ㄈㄤ", wadeGiles: "yüan³-fang¹", yale: "ywǎn-fāng", gwoyeu: "yeuanfang" },
  { hanzi: "暈", pinyin: "yùn", zhuyin: "ㄩㄣˋ", wadeGiles: "yün⁴", yale: "yùn", gwoyeu: "yunn" },
  { hanzi: "穿", pinyin: "chuān", zhuyin: "ㄔㄨㄢ", wadeGiles: "chʻuan¹", yale: "chwān", gwoyeu: "chuan" },
  { hanzi: "串", pinyin: "chuàn", zhuyin: "ㄔㄨㄢˋ", wadeGiles: "chʻuan⁴", yale: "chwàn", gwoyeu: "chuann" },
  { hanzi: "最近", pinyin: "zuìjìn", zhuyin: "ㄗㄨㄟˋ ㄐㄧㄣˋ", wadeGiles: "tsui⁴-chin⁴", yale: "dzwèi-jìn", gwoyeu: "tzueyjinn" },
  { hanzi: "罪", pinyin: "zuì", zhuyin: "ㄗㄨㄟˋ", wadeGiles: "tsui⁴", yale: "dzwèi", gwoyeu: "tzuey" },
  { hanzi: "昨日", pinyin: "zuóri", full: "zuórì", zhuyin: "ㄗㄨㄛˊ ˙ㄖ", wadeGiles: "tso²-jih⁵", yale: "dzwó-r", gwoyeu: "tzwo.ryh" },
  { hanzi: "坐下", pinyin: "zuòxia", full: "zuòxià", zhuyin: "ㄗㄨㄛˋ ˙ㄒㄧㄚ", wadeGiles: "tso⁴-hsia⁵", yale: "dzwò-sya", gwoyeu: "tzuoh.shiah" },
  { hanzi: "蘇州", pinyin: "Sūzhōu", zhuyin: "ㄙㄨ ㄓㄡ", wadeGiles: "Su¹-chou¹", yale: "Sū-jōu", gwoyeu: "Sujou" },
  { hanzi: "速度", pinyin: "sùdu", full: "sùdù", zhuyin: "ㄙㄨˋ ˙ㄉㄨ", wadeGiles: "su⁴-tu⁵", yale: "sù-du", gwoyeu: "suh.duh" },
  { hanzi: "搜索", pinyin: "sōusuǒ", zhuyin: "ㄙㄡ ㄙㄨㄛˇ", wadeGiles: "sou¹-so³", yale: "sōu-swǒ", gwoyeu: "sousuoo" },
  { hanzi: "所以", pinyin: "suǒyǐ", zhuyin: "ㄙㄨㄛˇ ㄧˇ", wadeGiles: "so³-i³", yale: "swǒ-yǐ", gwoyeu: "suooyii" },
  { hanzi: "色彩", pinyin: "sècǎi", zhuyin: "ㄙㄜˋ ㄘㄞˇ", wadeGiles: "sê⁴-tsʻai³", yale: "sè-tsǎi", gwoyeu: "sehtsae" },
  { hanzi: "森林", pinyin: "sēnlín", zhuyin: "ㄙㄣ ㄌㄧㄣˊ", wadeGiles: "sên¹-lin²", yale: "sēn-lín", gwoyeu: "senlin" },
  { hanzi: "生日", pinyin: "shēngri", full: "shēngrì", zhuyin: "ㄕㄥ ˙ㄖ", wadeGiles: "shêng¹-jih⁵", yale: "shēng-r", gwoyeu: "sheng.ryh" },
  { hanzi: "聲音", pinyin: "shēngyīn", zhuyin: "ㄕㄥ ㄧㄣ", wadeGiles: "shêng¹-yin¹", yale: "shēng-yīn", gwoyeu: "shengin" },
  { hanzi: "書法", pinyin: "shūfǎ", zhuyin: "ㄕㄨ ㄈㄚˇ", wadeGiles: "shu¹-fa³", yale: "shū-fǎ", gwoyeu: "shufaa" },
  { hanzi: "睡眠", pinyin: "shuìmián", zhuyin: "ㄕㄨㄟˋ ㄇㄧㄢˊ", wadeGiles: "shui⁴-mien²", yale: "shwèi-myán", gwoyeu: "shueymian" },
  { hanzi: "順利", pinyin: "shùnlì", zhuyin: "ㄕㄨㄣˋ ㄌㄧˋ", wadeGiles: "shun⁴-li⁴", yale: "shwùn-lì", gwoyeu: "shuennlih" },
  { hanzi: "軟件", pinyin: "ruǎnjiàn", zhuyin: "ㄖㄨㄢˇ ㄐㄧㄢˋ", wadeGiles: "juan³-chien⁴", yale: "rwǎn-jyàn", gwoyeu: "roanjiann" },
  { hanzi: "容易", pinyin: "róngyi", full: "róngyì", zhuyin: "ㄖㄨㄥˊ ˙ㄧ", wadeGiles: "jung²-i⁵", yale: "rúng-yi", gwoyeu: "rong.yih" },
  { hanzi: "仍然", pinyin: "réngrán", zhuyin: "ㄖㄥˊ ㄖㄢˊ", wadeGiles: "jêng²-jan²", yale: "réng-rán", gwoyeu: "rengran" },
  { hanzi: "熱情", pinyin: "rèqíng", zhuyin: "ㄖㄜˋ ㄑㄧㄥˊ", wadeGiles: "jê⁴-chʻing²", yale: "rè-chíng", gwoyeu: "rehchyng" },
];
